name: Breast Cancer ML API CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run model training test
      run: |
        python src/train_model.py
    
    - name: Verify model training completed
      run: |
        echo "✅ Model training test passed"

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t breast-cancer-api .
    
    - name: Test Docker image
      run: |
        echo "✅ Docker build completed successfully"

    - name: Log workflow result
      run: |
        echo "✅ CI/CD Pipeline completed successfully"